### ISSUE TITLE
如何同时显示 markdown 和 exmaple ？

### ISSUE THREAD

**Issue by zzswang** [benjycui/bisheng-plugin-react#5]
请教 如何在output 里同时显示 markdown 和 example

比如 MD 里原文是，

<pre>
This is a button:

```jsx
import { Button } from 'antd';
ReactDOM.render(<Button>Click!</Button>, mountNode);
```
</pre>

希望显示成

``` jsx
import { Button } from 'antd';
ReactDOM.render(<Button>Click!</Button>, mountNode);
```

<button class="btn btn-primary"> Click </button>

**Comment by benjycui** [comment]
现在只能写两份。。。。

**Comment by benjycui** [comment]
这种需求看来还是有的，但我暂时没有想到优雅的解决方法。。

**Comment by zzswang** [comment]
我看 ant-design 上 貌似是 写一份，不知道咋弄得。

**Comment by zzswang** [comment]
试了一下午，但是还是没搞定。主要是不太了解 babel 的操作。我的想法大约是

在jsonml-react-loader.js 文件中的 91 行位置，不直接调用 replaceWith，这里面没法调用 replaceWithMutiple()

大约是因为在一个循环里？

所以用cache接住，然后在循坏外 试图插入新的节点，而不是replace。

但是不知道为啥，insert不起作用。

@benjycui 能否帮忙看看 babel 如何插入节点
```
        const coceFunction = types.functionExpression(null, [], codeBlock);
        // path.replaceWith(coceFunction);
        // path.replaceWithMultiple();
        cache.push({path, node: coceFunction});
      }
    },
  });

  cache.forEach(item => item.path.insertBefore(item.node));
```

**Comment by benjycui** [comment]
不建议插入节点，因为不同的人的需求不一样，可能使出现在演示的上面、下面，或者像 ant.design 这样放在不同的组件下展示。

可以先写个 [插件](https://github.com/benjycui/bisheng/blob/master/docs/plugin.md)，在 `lib/node.js` 里面把代码先拷贝一份到别的地方。

**Comment by zzswang** [comment]
感觉一个额外的插件有点浪费，毕竟绝大部分逻辑都是一样的。

或者这个插件 加一个开关怎么样？ 比如：

```
module.exports = {
  plugins: ['bisheng-plugin-react?lang=jsx&pre=true'],
};
```

**Comment by benjycui** [comment]
https://github.com/benjycui/bisheng-plugin-react
